Repository Shubham-com/Training_CRUD_Operations, pull requests merged in 2022-10, with the labels that each got.

#1 Find a subject by name
  src/main/java/com/incture/training/subject/SubjectController.java
Labels: hactoberfest accepted, hactoberfest

#2 Update SubjectController.java
  src/main/java/com/incture/training/subject/SubjectController.java
Labels: hactoberfest accepted

#3 Delete Subject by name
  src/main/java/com/incture/training/subject/SubjectController.java
Labels: hactoberfest accepted

#4 Update SubjectService.java
  src/main/java/com/incture/training/subject/SubjectService.java
Labels: hactoberfest

#5 Update SubjectController.java
  src/main/java/com/incture/training/subject/SubjectController.java
Labels: hactoberfest

#6 Add updateSub in service class
  src/main/java/com/incture/training/subject/SubjectService.java
Labels: hactoberfest

#7 Modify updateSub
  src/main/java/com/incture/training/subject/SubjectController.java
Labels: hactoberfest
